name: build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux

    steps:
      - name: 'Download jextract'
        id: jextract
        uses: oracle-actions/setup-java@v1.1.1
        with:
          install: false
          uri: https://download.java.net/java/early_access/jextract/2/openjdk-19-jextract+2-3_${{ matrix.TARGET }}-x64_bin.tar.gz

      - name: 'Extract jextract'
        shell: sh
        run: |
          mkdir -p /tmp/jextract
          tar --strip-components=1 -xvf ${{ steps.jextract.outputs.archive }} -C /tmp/jextract
          ls -lah /tmp/jextract

      - name: 'Download JDK 19'
        id: jdk_19
        uses: oracle-actions/setup-java@v1.1.1
        with:
          website: jdk.java.net
          release: 19
          install: true

      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: install deps
        shell: bash
        run: |
          make install-deps

      - name: make jar
        shell: bash
        run: |
          export PATH=${PATH}:/tmp/jextract/bin

          make jar name=avcodec
          make jar name=avdevice
          make jar name=avfilter
          make jar name=avformat
          make jar name=avutil
          make jar name=postproc
          make jar name=swresample
          make jar name=swscale

      - name: upload platform-specific JAR to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: lib*/target/*.jar
          if-no-files-found: error
          retention-days: 1

  access-jars:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: download JARs
        uses: actions/download-artifact@v3
        with:
          path: target/jars
      - name: test presence
        run: |
          ls -lah target/jars/artifact
