name: build and release

on:
  push:
    branches: [ main ]

jobs:
  deploy-jars:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux

    steps:
      - name: 'Download JDK 19+jextract'
        id: download_jdk_19
        uses: oracle-actions/setup-java@v1.1.1
        with:
          install: true
          uri: https://download.java.net/java/early_access/jextract/2/openjdk-19-jextract+2-3_${{ matrix.TARGET }}-x64_bin.tar.gz

      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: install deps
        shell: bash
        run: |
          make install-deps

      - name: Publish package
        run: |
          make deploy name=avcodec
          make deploy name=avdevice
          make deploy name=avfilter
          make deploy name=avformat
          make deploy name=avutil
          make deploy name=postproc
          make deploy name=swresample
          make deploy name=swscale
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload platform-specific JAR to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: lib*/target/*.jar
          if-no-files-found: error
          retention-days: 1

  make-gh-release:
    runs-on: ubuntu-latest
    needs: deploy-jars
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: install deps
        shell: bash
        run: |
          make install-deps

      - name: download JARs
        uses: actions/download-artifact@v3
        with:
          path: target/jars

      - name: 'make release'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_RELEASE_TOKEN }}
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
          title: jtesseract ${{ steps.version.outputs.version }} release
          files: |
            LICENSE
            target/jars/artifact/*.jar
